<!doctype html>































<html
  class="not-ready lg:text-base"
  style="--bg: #faf8f1"
  lang="zh-tw"
>
  <head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta
    name="viewport"
    content="width=device-width, initial-scale=1, shrink-to-fit=no"
  />

  
  <title>例外處理 - seansie&#39;s blog</title>

  
  <meta name="theme-color" />

  
  
  
  
  <meta name="description" content="在程式執行中，總會遇到一些不可預期的錯誤，例如資料損毀，網路不通，或是使用者打錯字等等，這個時候總不能直接讓程式當機吧。
因此python提供了一個機制可以有效的處理這些錯誤，也就是例外處理，又名 try-except ，格式如下。
try: (1) except 錯誤名稱： （2） 區塊（1）請填入要嘗試（也就是可能會發生錯誤需要處理的程式碼）的程式碼 區塊（2）是當 except 後面的填入的錯位出現時，要如何處理的程式碼，我把他叫做例外處理。 在執行期間，try中的程式碼（區塊1）會先被執行，若有發生符合 except的錯誤名稱之錯誤，就會執行except後面的例外處理的部分，來處理錯誤。
例子 以下程式以除法計算機爲例子，正常四則運算之下除數不得爲零，因此如果在 python 中執行該運算會發生 ZeroDivisionError 錯誤，因此會執行(2)的區塊，告訴使用者除數不得爲零。
try: c=(a/b) #區塊（1） except ZeroDivisionError: print(&#34;除數不得爲0&#34;) #區塊（2） print(c) 以下提供兩種執行結果，一種是沒有錯誤的，另一種是有錯誤（除以0）因此有執行到例外處理的部分的。
錯誤列表 " />
  <meta name="author" content="seansie&#39;s blog" />
  

  
  
  
  
  
  
  <link rel="preload stylesheet" as="style" href="https://seansie0830.github.io/main.min.css" />

  
  
  
  
  
  <link rel="preload" as="image" href="https://seansie0830.github.io/theme.png" />

  
  
  
  
  

  
  
  

  
  
  <script
    defer
    src="https://seansie0830.github.io/highlight.min.js"
    onload="hljs.initHighlightingOnLoad();"
  ></script>
  

  
  
  

  
  <link rel="icon" href="https://seansie0830.github.io/favicon.ico" />
  <link rel="apple-touch-icon" href="https://seansie0830.github.io/apple-touch-icon.png" />

  
  <meta name="generator" content="Hugo 0.125.4">

  
  
  
  
  


  
  
  <meta itemprop="name" content="例外處理">
  <meta itemprop="description" content="在程式執行中，總會遇到一些不可預期的錯誤，例如資料損毀，網路不通，或是使用者打錯字等等，這個時候總不能直接讓程式當機吧。
因此python提供了一個機制可以有效的處理這些錯誤，也就是例外處理，又名 try-except ，格式如下。
try: (1) except 錯誤名稱： （2） 區塊（1）請填入要嘗試（也就是可能會發生錯誤需要處理的程式碼）的程式碼 區塊（2）是當 except 後面的填入的錯位出現時，要如何處理的程式碼，我把他叫做例外處理。 在執行期間，try中的程式碼（區塊1）會先被執行，若有發生符合 except的錯誤名稱之錯誤，就會執行except後面的例外處理的部分，來處理錯誤。
例子 以下程式以除法計算機爲例子，正常四則運算之下除數不得爲零，因此如果在 python 中執行該運算會發生 ZeroDivisionError 錯誤，因此會執行(2)的區塊，告訴使用者除數不得爲零。
try: c=(a/b) #區塊（1） except ZeroDivisionError: print(&#34;除數不得爲0&#34;) #區塊（2） print(c) 以下提供兩種執行結果，一種是沒有錯誤的，另一種是有錯誤（除以0）因此有執行到例外處理的部分的。
錯誤列表 ">
  <meta itemprop="datePublished" content="2024-07-16T15:35:59+08:00">
  <meta itemprop="dateModified" content="2024-07-16T15:35:59+08:00">
  <meta itemprop="wordCount" content="31">
  
  <meta property="og:url" content="https://seansie0830.github.io/posts/py-new-tutorial8/">
  <meta property="og:site_name" content="seansie&#39;s blog">
  <meta property="og:title" content="例外處理">
  <meta property="og:description" content="在程式執行中，總會遇到一些不可預期的錯誤，例如資料損毀，網路不通，或是使用者打錯字等等，這個時候總不能直接讓程式當機吧。
因此python提供了一個機制可以有效的處理這些錯誤，也就是例外處理，又名 try-except ，格式如下。
try: (1) except 錯誤名稱： （2） 區塊（1）請填入要嘗試（也就是可能會發生錯誤需要處理的程式碼）的程式碼 區塊（2）是當 except 後面的填入的錯位出現時，要如何處理的程式碼，我把他叫做例外處理。 在執行期間，try中的程式碼（區塊1）會先被執行，若有發生符合 except的錯誤名稱之錯誤，就會執行except後面的例外處理的部分，來處理錯誤。
例子 以下程式以除法計算機爲例子，正常四則運算之下除數不得爲零，因此如果在 python 中執行該運算會發生 ZeroDivisionError 錯誤，因此會執行(2)的區塊，告訴使用者除數不得爲零。
try: c=(a/b) #區塊（1） except ZeroDivisionError: print(&#34;除數不得爲0&#34;) #區塊（2） print(c) 以下提供兩種執行結果，一種是沒有錯誤的，另一種是有錯誤（除以0）因此有執行到例外處理的部分的。
錯誤列表 ">
  <meta property="og:locale" content="zh-tw">
  <meta property="og:type" content="article">
    <meta property="article:section" content="posts">
    <meta property="article:published_time" content="2024-07-16T15:35:59+08:00">
    <meta property="article:modified_time" content="2024-07-16T15:35:59+08:00">

  
  <meta name="twitter:card" content="summary"><meta name="twitter:title" content="例外處理">
<meta name="twitter:description" content="在程式執行中，總會遇到一些不可預期的錯誤，例如資料損毀，網路不通，或是使用者打錯字等等，這個時候總不能直接讓程式當機吧。
因此python提供了一個機制可以有效的處理這些錯誤，也就是例外處理，又名 try-except ，格式如下。
try: (1) except 錯誤名稱： （2） 區塊（1）請填入要嘗試（也就是可能會發生錯誤需要處理的程式碼）的程式碼 區塊（2）是當 except 後面的填入的錯位出現時，要如何處理的程式碼，我把他叫做例外處理。 在執行期間，try中的程式碼（區塊1）會先被執行，若有發生符合 except的錯誤名稱之錯誤，就會執行except後面的例外處理的部分，來處理錯誤。
例子 以下程式以除法計算機爲例子，正常四則運算之下除數不得爲零，因此如果在 python 中執行該運算會發生 ZeroDivisionError 錯誤，因此會執行(2)的區塊，告訴使用者除數不得爲零。
try: c=(a/b) #區塊（1） except ZeroDivisionError: print(&#34;除數不得爲0&#34;) #區塊（2） print(c) 以下提供兩種執行結果，一種是沒有錯誤的，另一種是有錯誤（除以0）因此有執行到例外處理的部分的。
錯誤列表 ">

  
  
  
  <link rel="canonical" href="https://seansie0830.github.io/posts/py-new-tutorial8/" />
  
  
</head>

  <body class="text-black duration-200 ease-out dark:text-white">
    <header class="mx-auto flex h-[4.5rem] max-w-3xl px-8 lg:justify-center">
  <div class="relative z-50 mr-auto flex items-center">
    <a
      class="-translate-x-[1px] -translate-y-[1px] text-2xl font-semibold"
      href="https://seansie0830.github.io/"
      >seansie&#39;s blog</a
    >
    <div
      class="btn-dark text-[0] ml-4 h-6 w-6 shrink-0 cursor-pointer [background:url(./theme.png)_left_center/_auto_theme('spacing.6')_no-repeat] [transition:_background-position_0.4s_steps(5)] dark:[background-position:right]"
      role="button"
      aria-label="Dark"
    ></div>
  </div>

  <div
    class="btn-menu relative z-50 -mr-8 flex h-[4.5rem] w-[5rem] shrink-0 cursor-pointer flex-col items-center justify-center gap-2.5 lg:hidden"
    role="button"
    aria-label="Menu"
  ></div>

  

  <script>
    
    const htmlClass = document.documentElement.classList;
    setTimeout(() => {
      htmlClass.remove('not-ready');
    }, 10);

    
    const btnMenu = document.querySelector('.btn-menu');
    btnMenu.addEventListener('click', () => {
      htmlClass.toggle('open');
    });

    
    const metaTheme = document.querySelector('meta[name="theme-color"]');
    const lightBg = '#faf8f1'.replace(/"/g, '');
    const setDark = (isDark) => {
      metaTheme.setAttribute('content', isDark ? '#000' : lightBg);
      htmlClass[isDark ? 'add' : 'remove']('dark');
      localStorage.setItem('dark', isDark);
    };

    
    const darkScheme = window.matchMedia('(prefers-color-scheme: dark)');
    if (htmlClass.contains('dark')) {
      setDark(true);
    } else {
      const darkVal = localStorage.getItem('dark');
      setDark(darkVal ? darkVal === 'true' : darkScheme.matches);
    }

    
    darkScheme.addEventListener('change', (event) => {
      setDark(event.matches);
    });

    
    const btnDark = document.querySelector('.btn-dark');
    btnDark.addEventListener('click', () => {
      setDark(localStorage.getItem('dark') !== 'true');
    });
  </script>

  <div
    class="nav-wrapper fixed inset-x-0 top-full z-40 flex h-full select-none flex-col justify-center pb-16 duration-200 dark:bg-black lg:static lg:h-auto lg:flex-row lg:!bg-transparent lg:pb-0 lg:transition-none"
  >
    
    

    
  </div>
</header>


    <main
      class="prose prose-neutral relative mx-auto min-h-[calc(100%-9rem)] max-w-3xl px-8 pb-16 pt-12 dark:prose-invert"
    >
      

<article>
  <header class="mb-16">
    <h1 class="!my-0 pb-2.5">例外處理</h1>

    
    <div class="text-sm antialiased opacity-60">
      
      <time>Jul 16, 2024</time>
      
      
      
      
    </div>
    
  </header>

  <section><p>在程式執行中，總會遇到一些不可預期的錯誤，例如資料損毀，網路不通，或是使用者打錯字等等，這個時候總不能直接讓程式當機吧。</p>
<p>因此python提供了一個機制可以有效的處理這些錯誤，也就是例外處理，又名 <code>try-except</code> ，格式如下。</p>
<pre tabindex="0"><code>try:
	(1)
except 錯誤名稱：
	（2）
</code></pre><ul>
<li>區塊（1）請填入要嘗試（也就是可能會發生錯誤需要處理的程式碼）的程式碼</li>
<li>區塊（2）是當 <code>except</code>  後面的填入的錯位出現時，要如何處理的程式碼，我把他叫做例外處理。</li>
</ul>
<p>在執行期間，try中的程式碼（區塊1）會先被執行，若有發生符合 <code>except</code>的錯誤名稱之錯誤，就會執行<code>except</code>後面的例外處理的部分，來處理錯誤。</p>
<h2 id="例子">例子</h2>
<p>以下程式以除法計算機爲例子，正常四則運算之下除數不得爲零，因此如果在 <code>python</code>  中執行該運算會發生 <code>ZeroDivisionError</code> 錯誤，因此會執行(2)的區塊，告訴使用者除數不得爲零。</p>
<div class="highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-python" data-lang="python"><span style="display:flex;"><span><span style="color:#66d9ef">try</span>:
</span></span><span style="display:flex;"><span>	c<span style="color:#f92672">=</span>(a<span style="color:#f92672">/</span>b) <span style="color:#75715e">#區塊（1）</span>
</span></span><span style="display:flex;"><span><span style="color:#66d9ef">except</span> <span style="color:#a6e22e">ZeroDivisionError</span>:
</span></span><span style="display:flex;"><span>	print(<span style="color:#e6db74">&#34;除數不得爲0&#34;</span>) <span style="color:#75715e">#區塊（2）</span>
</span></span><span style="display:flex;"><span>
</span></span><span style="display:flex;"><span>print(c)
</span></span></code></pre></div><p>以下提供兩種執行結果，一種是沒有錯誤的，另一種是有錯誤（除以0）因此有執行到例外處理的部分的。</p>
<div class="highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-python" data-lang="python"></code></pre></div><h2 id="錯誤列表">錯誤列表</h2>
</section>

  
  

  
  
  
  
  <nav class="mt-24 flex rounded-lg bg-black/[3%] text-lg dark:bg-white/[8%]">
    
    <a
      class="flex w-1/2 items-center rounded-l-md p-6 pr-3 font-semibold no-underline hover:bg-black/[2%] dark:hover:bg-white/[3%]"
      href="https://seansie0830.github.io/posts/zj_a006/"
      ><span class="mr-1.5">←</span><span>zerojudge a006 程式碼</span></a
    >
    
    
    <a
      class="ml-auto flex w-1/2 items-center justify-end rounded-r-md p-6 pl-3 font-semibold no-underline hover:bg-black/[2%] dark:hover:bg-white/[3%]"
      href="https://seansie0830.github.io/posts/py-new-tutorial6/"
      ><span>字典(KV)資料庫</span><span class="ml-1.5">→</span></a
    >
    
  </nav>
  
  

  
  

  
  

  


  
</article>


    </main>

    <footer
  class="opaco mx-auto flex h-[4.5rem] max-w-3xl items-center px-8 text-[0.9em] opacity-60"
>
  <div class="mr-auto">
    &copy; 2024
    <a class="link" href="https://seansie0830.github.io/">seansie&#39;s blog</a>
  </div>
  <a class="link mx-6" href="https://gohugo.io/" rel="noopener" target="_blank"
    >Powered by Hugo️️</a
  >️
  <a
    class="link"
    href="https://github.com/nanxiaobei/hugo-paper"
    rel="noopener"
    target="_blank"
    >✎ Paper</a
  >
</footer>

  </body>
</html>
